use sakila;
select * from actor;
show tables;
select * from actor;
select * from film;
select * from customer;
select title from film;
select language_id from language;
select first_name from staff;
select distinct release_year from film;
select count(distinct store_id) from store;
select count(distinct staff_id) from staff;
select count(distinct rental_id) from rental;
select count(distinct rental_date) from rental;
select count(distinct last_name) from actor;
select length from film order by length desc limit 10;
select film_id from film where (select length from film order by length desc limit 10);
select first_name from actor where first_name like "scarlett";
select distinct title from film where title like "%armageddon%" and (length>100);
select count(distinct film_id) from film where special_features like "behind the scenes";
